version: '3.8'
services:
  web-jenkins:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=3000
    restart: always